In [2]:
from imports import *




git@github.com:stephenkipkurui/codeup-individual-project.git

<h1>:wave:Hello, my name is Oliver!</h1>
<div id="header" align="center">
    <img src="https://media.giphy.com/media/M9gbBd9nbDrOTu1Mqx/giphy.gif"width="150">
</div>

<h3>:mailbox: Reach me at:</h3>

<div id="badges">
    <a href = "https://www.linkedin.com/in/oliver-ton/">
         <img src="https://img.shields.io/badge/LinkedIn-blue?logo=linkedin&logoColor=white" alt="LinkedIn Badge"/>
    </a>
    <a href = "mailto:oliver.ton75@gmail.com">
        <img src="https://img.shields.io/badge/Gmail-D14836?logo=gmail&logoColor=white" alt="gmail Badge"/>
    </a>
</div>

---

<h3 align="left"> About Me: </h3>
<p>
- :seedling: I am currently a student at <a href ="https://codeup.com"><img src="https://img.shields.io/badge/Codeup-green?logo=Codeup&logoColor=white"></a>, Expected Graduation: June 2022
</p>
<p>
- :mortar_board: Texas State University alumni! BBA in Computer Infomation System(CIS) - August 2020
</p>
<p>
- :video_game: I play video games in my free time, you might able to find me on <img src="https://img.shields.io/badge/Steam-blue?logo=Steam&logoColor=white">
</p>

---

<h3 align="left">Tools:</h3>

![jupyter](https://img.shields.io/badge/-Jupyter_Lab-818589?style=for-the-badge&logo=jupyter&logoColor=orange) 
![pandas](https://img.shields.io/badge/-Pandas-321637?style=for-the-badge&logo=pandas&logoColor=white) 
![numpy](https://img.shields.io/badge/-NumPy-5092e4?style=for-the-badge&logo=numpy&logoColor=D4EFEB) 
![sns](https://img.shields.io/badge/-Seaborn-7a85bd?style=for-the-badge&logo=seaborn&logoColor=D4EFEB) 
![plt](https://img.shields.io/badge/-Matplotlib-095090?style=for-the-badge&logo=matplotlib&logoColor=D4EFEB)

![scipy](https://img.shields.io/badge/-SciPy-094e8b?style=for-the-badge&logo=scipy&logoColor=white) 
![sklearn](https://img.shields.io/badge/-SciKit--Learn-dc900e?style=for-the-badge&logo=scikit-learn&logoColor=white) 
![terminal](https://img.shields.io/badge/-Terminal-black?style=for-the-badge&logo=apple&logoColor=white) ![tableau](https://img.shields.io/badge/-Tableau-blue?style=for-the-badge&logo=tableau&logoColor=white) ![excel](https://img.shields.io/badge/-Excel-green?style=for-the-badge&logo=microsoft-excel&logoColor=white) ![google](https://img.shields.io/badge/-Google_Sheets-darkgreen?style=for-the-badge&logo=googlesheets&logoColor=white)  

---

<h3 align="left">Language:</h3>
<div>
    <img src="https://github.com/devicons/devicon/blob/master/icons/mysql/mysql-original-wordmark.svg" title="MySQL"  alt="MySQL" width="30" height="40"/>&nbsp;
    <img src="https://github.com/devicons/devicon/blob/master/icons/python/python-original.svg" title="Python" alt="Python" width="30" height="40"/>&nbsp;
    <img src="https://github.com/devicons/devicon/blob/master/icons/swift/swift-original.svg" title="Swift" alt="Swift" width="30" height="40"/>&nbsp;
    <img src="https://github.com/devicons/devicon/blob/master/icons/csharp/csharp-original.svg" title="C#" alt="C#" width="30" height="40"/>&nbsp;
    <img src="https://github.com/devicons/devicon/blob/master/icons/javascript/javascript-original.svg" title="JavaScript" alt="JavaScript" width="30" height="40"/>&nbsp;
</div>

<h3> :mailbox: Reach me at: </h3>

<div id="badges">
    <a href = "https://www.linkedin.com/in/hinzle/">
         <img src="https://img.shields.io/badge/LinkedIn-blue?logo=linkedin&logoColor=white" alt="LinkedIn Badge"/>
    </a>
    <a href = "mailto:foresthensley@gmail.com">
        <img src="https://img.shields.io/badge/Gmail-D14836?logo=gmail&logoColor=white" alt="gmail Badge"/>
    </a>
</div>

---

<h3>:star_struck: Favs: </h3>

![Adobe](https://img.shields.io/badge/adobe-%23FF0000.svg?style=for-the-badge&logo=adobe&logoColor=white)
![Anaconda](https://img.shields.io/badge/Anaconda-%2344A833.svg?style=for-the-badge&logo=anaconda&logoColor=white)
![Android](https://img.shields.io/badge/Android-3DDC84?style=for-the-badge&logo=android&logoColor=white)
![Arduino](https://img.shields.io/badge/-Arduino-00979D?style=for-the-badge&logo=Arduino&logoColor=white)
![Binance](https://img.shields.io/badge/Binance-FCD535?style=for-the-badge&logo=binance&logoColor=white)
![Bitcoin](https://img.shields.io/badge/Bitcoin-000?style=for-the-badge&logo=bitcoin&logoColor=white)
![C](https://img.shields.io/badge/c-%2300599C.svg?style=for-the-badge&logo=c&logoColor=white)
![Canva](https://img.shields.io/badge/Canva-%2300C4CC.svg?style=for-the-badge&logo=Canva&logoColor=white)
![CSS3](https://img.shields.io/badge/css3-%231572B6.svg?style=for-the-badge&logo=css3&logoColor=white)
![Dogecoin](https://img.shields.io/badge/dogecoin-B59A30?style=for-the-badge&logo=dogecoin&logoColor=white)
![Ethereum](https://img.shields.io/badge/Ethereum-3C3C3D?style=for-the-badge&logo=Ethereum&logoColor=white)
![Git](https://img.shields.io/badge/git-%23F05033.svg?style=for-the-badge&logo=git&logoColor=white)
![GitHub](https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white)
![Google Cloud](https://img.shields.io/badge/GoogleCloud-%234285F4.svg?style=for-the-badge&logo=google-cloud&logoColor=white)
![Google](https://img.shields.io/badge/google-4285F4?style=for-the-badge&logo=google&logoColor=white)
![HTML5](https://img.shields.io/badge/html5-%23E34F26.svg?style=for-the-badge&logo=html5&logoColor=white)
![IOS](https://img.shields.io/badge/iOS-000000?style=for-the-badge&logo=ios&logoColor=white)
![Jupyter Notebook](https://img.shields.io/badge/jupyter-%23FA0F00.svg?style=for-the-badge&logo=jupyter&logoColor=white)
![jupyter](https://img.shields.io/badge/-Jupyter_Lab-818589?style=for-the-badge&logo=jupyter&logoColor=orange)
![Kaggle](https://img.shields.io/badge/Kaggle-035a7d?style=for-the-badge&logo=kaggle&logoColor=white)
![Kubernetes](https://img.shields.io/badge/kubernetes-%23326ce5.svg?style=for-the-badge&logo=kubernetes&logoColor=white)
![Mac OS](https://img.shields.io/badge/mac%20os-000000?style=for-the-badge&logo=macos&logoColor=F0F0F0)
![Markdown](https://img.shields.io/badge/markdown-%23000000.svg?style=for-the-badge&logo=markdown&logoColor=white)
<img src="https://github.com/devicons/devicon/blob/master/icons/matlab/matlab-original.svg" title="MATLAB" alt="MATLAB" width="23" height="31"/>&nbsp;
![Microsoft Office](https://img.shields.io/badge/Microsoft_Office-D83B01?style=for-the-badge&logo=microsoft-office&logoColor=white)
![Microsoft](https://img.shields.io/badge/Microsoft-0078D4?style=for-the-badge&logo=microsoft&logoColor=white)
![MySQL](https://img.shields.io/badge/mysql-%2300f.svg?style=for-the-badge&logo=mysql&logoColor=white)
![numpy](https://img.shields.io/badge/-NumPy-5092e4?style=for-the-badge&logo=numpy&logoColor=D4EFEB)
![pandas](https://img.shields.io/badge/-Pandas-321637?style=for-the-badge&logo=pandas&logoColor=white)
![plt](https://img.shields.io/badge/-Matplotlib-095090?style=for-the-badge&logo=matplotlib&logoColor=D4EFEB)
![Python](https://img.shields.io/badge/python-3670A0?style=for-the-badge&logo=python&logoColor=ffdd54)
![scipy](https://img.shields.io/badge/-SciPy-094e8b?style=for-the-badge&logo=scipy&logoColor=white)
![sklearn](https://img.shields.io/badge/-SciKit--Learn-dc900e?style=for-the-badge&logo=scikit-learn&logoColor=white)
![Slack](https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white)
![sns](https://img.shields.io/badge/-Seaborn-7a85bd?style=for-the-badge&logo=seaborn&logoColor=D4EFEB)
![Spotify](https://img.shields.io/badge/Spotify-1ED760?style=for-the-badge&logo=spotify&logoColor=white)
![Stack Overflow](https://img.shields.io/badge/-Stackoverflow-FE7A16?style=for-the-badge&logo=stack-overflow&logoColor=white)
![tableau](https://img.shields.io/badge/-Tableau-blue?style=for-the-badge&logo=tableau&logoColor=white)
![terminal](https://img.shields.io/badge/-Terminal-black?style=for-the-badge&logo=apple&logoColor=white)
![Trello](https://img.shields.io/badge/Trello-%23026AA7.svg?style=for-the-badge&logo=Trello&logoColor=white)
![Ubuntu](https://img.shields.io/badge/Ubuntu-E95420?style=for-the-badge&logo=ubuntu&logoColor=white)
![Vim](https://img.shields.io/badge/VIM-%2311AB00.svg?style=for-the-badge&logo=vim&logoColor=white)
![Visual Studio Code](https://img.shields.io/badge/Visual%20Studio%20Code-0078d7.svg?style=for-the-badge&logo=visual-studio-code&logoColor=white)
![Wikipedia](https://img.shields.io/badge/Wikipedia-%23000000.svg?style=for-the-badge&logo=wikipedia&logoColor=white)
![Windows](https://img.shields.io/badge/Windows-0078D6?style=for-the-badge&logo=windows&logoColor=white)
![Xbox](https://img.shields.io/badge/Hinzle2892-%23107C10.svg?style=for-the-badge&logo=Xbox&logoColor=white)


In [ ]:
from pandas_profiling import ProfileReport
from pydataset import data
df = data('tips')
profile=ProfileReport(df)
profile

[![Email](https://img.shields.io/badge/Gmail-EA4335?style=for-the-badge&logo=Gmail&logoColor=white)](foresthensley@gmail.com)

foresthensley@gmail.com

[![Linkedin](https://img.shields.io/badge/Linkedin-0A66C2?style=for-the-badge&logo=Linkedin&logoColor=white)](https://www.linkedin.com/in/forest-hensley-5389a889/)

In [14]:
y=[1 for x in range(0,100)]

In [16]:
sum([0 if  else 1 for i in y])

0

$Classificaion Project$

In [ ]:
index = ['Jack_a','Survivor_a']
col = ['Jack_p','Survivor_p' ]
pd.DataFrame(confusion_matrix(y_train, y_pred), index=[str(i) for i in titanic_clf.classes_], columns=col)

Jack_p  Survivor_p
0     300          29
1      54         151

In [ ]:
pd.DataFrame([['true negative', 'false positive'],['false negative', 'true positive']], columns=['predict_death', 'predict_survive'], index=['actual_death', 'actual_survive'])


predict_death predict_survive
actual_death     true negative  false positive
actual_survive  false negative   true positive

In [ ]:
clf = DecisionTreeClassifier(max_depth=3, random_state=123)
clf=clf.fit(X_train, y_train)

In [ ]:
clf.classes_

array([0, 1])

In [2]:
df = pd.DataFrame({
    'actual': ['c','b','b'],
    'prediction': ['c','b','b'],
})
df

actual prediction
0      c          c
1      b          b
2      b          b

In [3]:
conf=confusion_matrix(df.actual, df.prediction)
conf


array([[2, 0],
       [0, 1]])

In [4]:
conf[0][1]

0

In [5]:
x=8*10**4

a=x-.2*x

b=.2*x

c=b-.3*b

d=b*.3

x,a,b,c,d

(80000, 64000.0, 16000.0, 11200.0, 4800.0)

### iPhone
- TP - unlock stakeholder
- FP - unlock hacker
- FN - locked stakeholder
- TN - locked hacker



### iPhone
- positive case: unlock correct face
- negative case: unlock wrong face
- TP - unlock stakeholder ; cost - happy stakeholder
- FP - lock correct face ; cost - unhappy stakeholder
- TN - unlock hacker ; cost - unhappy hacker
- FN - lock hacker ; cost - happy hacker
- precision

### Spam
- positive case: put junk mail in spam folder 
- negative case: put important mail in spame folder
- TP - junk in spam
- TN - mail in inbox
- FP - mail in spam
- FN - junk in inbox

# Train, Validate, Test Split

## sk.train_test_split

In [6]:
# train, test = train_test_split(df, test_size=.2, random_state=123, stratify=df.organize_data_by_this_column)
# train, validate = train_test_split(train, test_size=.3, random_state=123, stratify=train.survived)

# Impute

## 1. Create the imputer object:

In [7]:
# imputer = sk.SimpleImputer(missing_values = None, strategy='most_frequent')

# strategies: mean, median, most_frequent

## 2. Fit to train:

In [8]:
# imputer = sk.imputer.fit(train[['column_to_fit']])

## 3. Transform data:

In [9]:
# train[['column_to_impute']] = sk.imputer.transform(train[['column_to_impute']])

In [10]:
randorr=np.random.randint(0,99,1)
randorr

array([66])